// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OzelDersYerim.Data.Concrete.EfCore.Context;

#nullable disable

namespace OzelDersYerim.Data.Migrations
{
    [DbContext(typeof(OzelDersYerimContext))]
    partial class OzelDersYerimContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("OzelDersYerim.Entity.Concrete.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Branches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchName = "Matematik",
                            ImageUrl = "mat.png",
                            Url = "matematik"
                        },
                        new
                        {
                            Id = 2,
                            BranchName = "Kimya",
                            ImageUrl = "kimya.png",
                            Url = "kimya"
                        },
                        new
                        {
                            Id = 3,
                            BranchName = "İngilizce",
                            ImageUrl = "ing.png",
                            Url = "ingilizce"
                        },
                        new
                        {
                            Id = 4,
                            BranchName = "Müzik",
                            ImageUrl = "müzik.png",
                            Url = "muzik"
                        },
                        new
                        {
                            Id = 5,
                            BranchName = "Türkçe",
                            ImageUrl = "turkce.png",
                            Url = "turkce"
                        },
                        new
                        {
                            Id = 6,
                            BranchName = "Bilgisayar",
                            ImageUrl = "bilgisayar.png",
                            Url = "bilgisayar"
                        });
                });

            modelBuilder.Entity("OzelDersYerim.Entity.Concrete.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "24 Yaşındayım.Yazılım eğitimi alıyorum.Yeni programlama dilleri üzerinde kendimi geliştirmek ve ders almak istiyorum.",
                            Age = "24",
                            FirstName = "Mert Korkut",
                            ImageUrl = "1.png",
                            LastName = "Muslu",
                            Url = "ogrenci-mert-korkut-muslu"
                        },
                        new
                        {
                            Id = 2,
                            About = "24 Yaşındayım.Elektirk-elektronik mühendisiyim ancak şu sıralar yazılım eğitimi alıyorum.Kendimi bu alanda geliştirmek istiyorum.",
                            Age = "28",
                            FirstName = "Cemre ",
                            ImageUrl = "2.png",
                            LastName = "Şenel",
                            Url = "ogrenci-cemre-senel"
                        },
                        new
                        {
                            Id = 3,
                            About = "Kendimi her alanda gelişime açık hissediyorum. Back-end developer alanında çalışmak istediğim içinde özellikle bu alanda kendime birşeyler katmak istiyorum.",
                            Age = "23",
                            FirstName = "Harun ",
                            ImageUrl = "3.png",
                            LastName = "Özer",
                            Url = "ogrenci-harun-ozer"
                        },
                        new
                        {
                            Id = 4,
                            About = "Yeni mezun bir sağlıkçı olarak Kpss sınavlarına hazırlanmak için matematik dersleri almak istiyorum.",
                            Age = "20",
                            FirstName = "Senem",
                            ImageUrl = "4.png",
                            LastName = "Öztürk",
                            Url = "ogrenci-senem-ozturk"
                        },
                        new
                        {
                            Id = 5,
                            About = "Matematik derslerinde çok zorlanıyorum.",
                            Age = "14",
                            FirstName = "Zeynep",
                            ImageUrl = "5.png",
                            LastName = "Aslan",
                            Url = "ogrenci-zeynep-aslan"
                        },
                        new
                        {
                            Id = 6,
                            About = "Merhaba.Herhangi bir müzik aleti çalmayı öğrenmek için buradayım !.",
                            Age = "22",
                            FirstName = "Kemal Emre",
                            ImageUrl = "6.png",
                            LastName = "Erol",
                            Url = "ogrenci-kemal-emre-erol"
                        },
                        new
                        {
                            Id = 7,
                            About = "Lise öğrencisiyim.Üniversite sınavları için Kimya dersleri almak istiyorum.",
                            Age = "17",
                            FirstName = "Aslı",
                            ImageUrl = "7.png",
                            LastName = "Yıldız",
                            Url = "ogrenci-asli-yildiz"
                        });
                });

            modelBuilder.Entity("OzelDersYerim.Entity.Concrete.StudentTeacher", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("StudentTeachers", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            StudentId = 1,
                            TeacherId = 2
                        },
                        new
                        {
                            StudentId = 2,
                            TeacherId = 1
                        },
                        new
                        {
                            StudentId = 2,
                            TeacherId = 3
                        },
                        new
                        {
                            StudentId = 3,
                            TeacherId = 3
                        },
                        new
                        {
                            StudentId = 3,
                            TeacherId = 4
                        },
                        new
                        {
                            StudentId = 4,
                            TeacherId = 5
                        },
                        new
                        {
                            StudentId = 5,
                            TeacherId = 6
                        },
                        new
                        {
                            StudentId = 6,
                            TeacherId = 1
                        },
                        new
                        {
                            StudentId = 7,
                            TeacherId = 2
                        },
                        new
                        {
                            StudentId = 7,
                            TeacherId = 7
                        });
                });

            modelBuilder.Entity("OzelDersYerim.Entity.Concrete.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Experince")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PricePerHour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Mimar Sinan Güzel Sanatlar Üniversitesi Konservatuar mezunuyum. Uzmanlık alanım Piyano olamakla beraber keman ve gitar dersleri de vermekteyim.",
                            Age = "39",
                            BranchId = 4,
                            Experince = "15",
                            FirstName = "Ahmet",
                            Gender = "Erkek",
                            ImageUrl = "10.png",
                            LastName = "Yılmaz",
                            Location = "Beşiktaş",
                            Phone = "05550005500",
                            PricePerHour = 450m,
                            Url = "ogretmen-ahmet-yilmaz"
                        },
                        new
                        {
                            Id = 2,
                            About = "İngilizce Öğretmeniyim. Her türlü İngilizce sınavlarına hazırlık konusunda ders vermekteyim.",
                            Age = "27",
                            BranchId = 3,
                            Experince = "5",
                            FirstName = "Arzu",
                            Gender = "Kadın",
                            ImageUrl = "11.png",
                            LastName = "Doğramacı",
                            Location = "Şişli",
                            Phone = "05550005501",
                            PricePerHour = 300m,
                            Url = "ogretmen-arzu-dogramaci"
                        },
                        new
                        {
                            Id = 3,
                            About = "İlköğretim-lise düzeyinde matematik dersleri verilir. Sınavlar için fazladan etüt alabilirsiniz.",
                            Age = "42",
                            BranchId = 1,
                            Experince = "",
                            FirstName = "Serdar",
                            Gender = "Erkek",
                            ImageUrl = "12.png",
                            LastName = "Kulbilge",
                            Location = "Aksaray",
                            Phone = "05550005502",
                            PricePerHour = 250m,
                            Url = "ogretmen-serdar-kulbilge"
                        },
                        new
                        {
                            Id = 4,
                            About = "Boğaziçi Üniversitesi Mezunuyum. 28 yaşındayım. Özel bir lisede Kimya Öğretmenliği yapıyorum.",
                            Age = "28",
                            BranchId = 2,
                            Experince = "6",
                            FirstName = "Hande",
                            Gender = "Kadın",
                            ImageUrl = "13.png",
                            LastName = "Yıldırım",
                            Location = "Etiler",
                            Phone = "05550005503",
                            PricePerHour = 300m,
                            Url = "ogretmen-hande-yildirim"
                        },
                        new
                        {
                            Id = 5,
                            About = "Samsun 19 Mayıs Universitesi Matematik Bölümü mezunuyum. Aynı zamanda Elektro Gitar dersleri vermekteyim.",
                            Age = "30",
                            BranchId = 4,
                            Experince = "7",
                            FirstName = "Burak",
                            Gender = "Erkek",
                            ImageUrl = "14.png",
                            LastName = "Yılmaz",
                            Location = "Mecidiyeköy",
                            Phone = "05550005504",
                            PricePerHour = 400m,
                            Url = "ogretmen-burak-yilmaz"
                        },
                        new
                        {
                            Id = 6,
                            About = "Türk Dili Ve Edebiyatı, Türkçe, Dil Anlatım gibi dersler uzmanlık alanım olup, her türlü sınav için ders veriyorum.",
                            Age = "29",
                            BranchId = 5,
                            Experince = "7",
                            FirstName = "Hasan Can",
                            Gender = "Erkek",
                            ImageUrl = "15.png",
                            LastName = "Güzel",
                            Location = "Beşiktaş",
                            Phone = "05550005505",
                            PricePerHour = 200m,
                            Url = "ogretmen-hasan-can-guzel"
                        },
                        new
                        {
                            Id = 7,
                            About = "Back-End ve Front-End development konularında A'dan Z'ye eğitim vermekteyim. Sektörde Senior Developer olarak çalıştım.",
                            Age = "42",
                            BranchId = 6,
                            Experince = "21",
                            FirstName = "Hakkı ",
                            Gender = "Erkek",
                            ImageUrl = "16.png",
                            LastName = "Sarıca",
                            Location = "Esenler",
                            Phone = "05550005505",
                            PricePerHour = 700m,
                            Url = "ogretmen-hakki-sarica"
                        });
                });

            modelBuilder.Entity("OzelDersYerim.Entity.Concrete.StudentTeacher", b =>
                {
                    b.HasOne("OzelDersYerim.Entity.Concrete.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OzelDersYerim.Entity.Concrete.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("OzelDersYerim.Entity.Concrete.Teacher", b =>
                {
                    b.HasOne("OzelDersYerim.Entity.Concrete.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });
#pragma warning restore 612, 618
        }
    }
}
